name: Create Issue

on:
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -d '{"title":"Automatic Issue","body":"This issue was created automatically by a GitHub Actions workflow.","assignees":["ysdzm"]}' \
        https://api.github.com/repos/${{ github.repository }}/issues
